version: '2'
services:
  cfcorp-site:
    image: dhvogel/cfcorp-site:1.1
    container_name: cfcorp-site
    ports:
     - "80:3000"
    links:
     - cfcorp-workouts-service
  cfcorp-workouts-service:
    image: dhvogel/cfcorp-workouts-service:1.1
    container_name: cfcorp-workouts-service
    ports:
     - "9000:9000"
    depends_on:
     - mongo
    links:
     - mongo
    environment:
     - NODE_ENV=production
  mongo:
    image: mongo
    container_name: mongo
    ports:
     - "27017:27017"
